Repository tukcom2023CD/RISING, pull requests merged in 2023-01, with the labels that each got.

#14 [Chore/#8] docker-compose 세팅
  backend/build.gradle
  backend/src/main/resources/application.yml
  docker-compose.yml
  frontend/Dockerfile
Labels: 환경설정

#26 [FE/feat/#20] 질문 답변 페이지 퍼블리싱
  frontend/src/components/Ans.tsx
  frontend/src/components/AnswerIndex.tsx
  frontend/src/components/Btn.tsx
  frontend/src/components/ContentIndex.tsx
  frontend/src/components/NavBar.tsx
  frontend/src/components/Tag.tsx
  frontend/src/components/TitleIndex.tsx
  frontend/src/images/answer1.png
  frontend/src/images/answer2.png
  frontend/src/images/answer3.png
  frontend/src/images/content1.png
  frontend/src/images/content2.png
  frontend/src/images/content3.png
  frontend/src/images/title1.png
  frontend/src/images/title2.png
  frontend/src/images/title3.png
  frontend/src/page/AnsPage.tsx
  frontend/src/utils/ColorSystem.tsx
  frontend/tailwind.config.js
Labels: 기능구현

#29 [BE/feat/#22] Post Create api 구현
  backend/src/main/java/com/rising/backend/domain/comment/domain/controller/CommentController.java
  backend/src/main/java/com/rising/backend/domain/comment/dto/request/CommentRequest.java
  backend/src/main/java/com/rising/backend/domain/comment/repository/CommentRepository.java
  backend/src/main/java/com/rising/backend/domain/comment/service/CommentService.java
  backend/src/main/java/com/rising/backend/domain/post/controller/PostController.java
  backend/src/main/java/com/rising/backend/domain/post/domain/PostType.java
  backend/src/main/java/com/rising/backend/domain/post/dto/mapper/PostMapper.java
  backend/src/main/java/com/rising/backend/domain/post/dto/request/PostCreateRequestDto.java
  backend/src/main/java/com/rising/backend/domain/post/repository/PostRepository.java
  backend/src/main/java/com/rising/backend/domain/post/service/PostService.java
  backend/src/main/java/com/rising/backend/domain/user/service/UserService.java
Labels: 기능구현

#32 BE/feat/#23
  backend/src/main/java/com/rising/backend/domain/comment/controller/CommentController.java
  backend/src/main/java/com/rising/backend/domain/post/dto/mapper/PostMapper.java
  backend/src/main/java/com/rising/backend/domain/user/controller/UserController.java
  backend/src/main/java/com/rising/backend/domain/user/dto/UserRequest.java
  backend/src/main/java/com/rising/backend/domain/user/repository/UserRepository.java
  backend/src/main/java/com/rising/backend/domain/user/service/LoginService.java
  backend/src/main/java/com/rising/backend/domain/user/service/UserService.java
Labels: 기능구현

#35 [Be/refactor/#31] post create api 수정
  backend/gradle/properties.java
  backend/src/main/java/com/rising/backend/domain/post/controller/PostController.java
  backend/src/main/java/com/rising/backend/domain/post/dto/PostDto.java
  backend/src/main/java/com/rising/backend/domain/post/dto/request/PostCreateRequestDto.java
  backend/src/main/java/com/rising/backend/domain/post/mapper/PostMapper.java
  backend/src/main/java/com/rising/backend/domain/post/service/PostService.java
  backend/src/main/java/com/rising/backend/domain/user/controller/UserController.java
  backend/src/main/java/com/rising/backend/domain/user/dto/UserDto.java
  backend/src/main/java/com/rising/backend/domain/user/mapper/UserMapper.java
  backend/src/main/java/com/rising/backend/domain/user/service/UserService.java
  backend/src/main/java/com/rising/backend/global/result/ResultCode.java
  backend/src/main/java/com/rising/backend/global/result/ResultResponse.java
Labels: 오류수정

#39 BE/feat/#36 Comment Create API 구현
  backend/src/main/java/com/rising/backend/domain/comment/controller/CommentController.java
  backend/src/main/java/com/rising/backend/domain/comment/domain/Comment.java
  backend/src/main/java/com/rising/backend/domain/comment/dto/CommentDto.java
  backend/src/main/java/com/rising/backend/domain/comment/dto/request/CommentRequest.java
  backend/src/main/java/com/rising/backend/domain/comment/mapper/CommentMapper.java
  backend/src/main/java/com/rising/backend/domain/comment/service/CommentService.java
  backend/src/main/java/com/rising/backend/domain/post/service/PostService.java
  backend/src/main/java/com/rising/backend/global/result/ResultCode.java
Labels: 기능구현

#41 [feat] 과외 채팅방 페이지 퍼블리싱
  frontend/src/App.tsx
  frontend/src/components/MentoNavBar.tsx
  frontend/src/images/profile.png
  frontend/src/images/send.png
  frontend/src/page/QuesChatPage.tsx
Labels: 기능구현

#45 [FE/feat/#43] 질문 작성 페이지, 과외 질문 작성 페이지 퍼블리싱
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Btn.tsx
  frontend/src/components/Index/AnsTitleIndex.tsx
  frontend/src/components/Index/EndIndex.tsx
  frontend/src/components/Index/KeywordIndex.tsx
  frontend/src/components/Index/QuesTitleIndex.tsx
  frontend/src/components/MentoNavBar.tsx
  frontend/src/components/NavBar.tsx
  frontend/src/components/QuesNavBar.tsx
  frontend/src/components/Select/KeywordSelect.tsx
  frontend/src/components/Select/data.ts
  frontend/src/page/AnsPage.tsx
  frontend/src/page/PrivateAnsCheckPage.tsx
  frontend/src/page/PrivateAnsPage.tsx
  frontend/src/page/PrivateQuesPage.tsx
  frontend/src/page/QuesPage.tsx
Labels: 기능구현

#47 [FE/feat/#42] 마이페이지 퍼블리싱
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Ans.tsx
  frontend/src/components/ChatBox.tsx
  frontend/src/components/Ques.tsx
  frontend/src/components/Tag.tsx
  frontend/src/images/pencil.png
  frontend/src/page/AnsPage.tsx
  frontend/src/page/MyPage.tsx
  frontend/src/page/PrivateAnsCheckPage.tsx
  frontend/src/page/PrivateAnsPage.tsx
  frontend/src/page/QuesChatPage.tsx
  frontend/src/page/QuesListPage.tsx
Labels: 기능구현

#50 [BE/chore/#40] RabbitMQ 세팅
  backend/build.gradle
  backend/src/main/java/com/rising/backend/domain/sharecoding/controller/CodeController.java
  backend/src/main/java/com/rising/backend/domain/sharecoding/domain/Act.java
  backend/src/main/java/com/rising/backend/domain/sharecoding/domain/Operation.java
  backend/src/main/java/com/rising/backend/global/config/RabbitConfig.java
  backend/src/main/java/com/rising/backend/global/config/StompConfig.java
  backend/src/main/java/com/rising/backend/global/constant/RabbitMQ.java
Labels: 환경설정

#54 [BE/feat/#53] : 질문 리스트 페이징 구현
  backend/src/main/java/com/rising/backend/domain/post/controller/PostController.java
  backend/src/main/java/com/rising/backend/domain/post/dto/PostDto.java
  backend/src/main/java/com/rising/backend/domain/post/mapper/PostMapper.java
  backend/src/main/java/com/rising/backend/domain/post/service/PostService.java
  backend/src/main/java/com/rising/backend/global/result/ResultCode.java
Labels: 기능구현

#61 [BE/feat/#59] userId로 post list 조회 및 memo 삭제
  backend/src/main/java/com/rising/backend/domain/post/controller/PostController.java
  backend/src/main/java/com/rising/backend/domain/post/domain/Post.java
  backend/src/main/java/com/rising/backend/domain/post/mapper/PostMapper.java
  backend/src/main/java/com/rising/backend/domain/post/repository/PostRepository.java
  backend/src/main/java/com/rising/backend/domain/post/service/PostService.java
  backend/src/main/java/com/rising/backend/global/result/ResultCode.java
  backend/src/main/resources/application.yml
  docker-compose.yml
Labels: 환경설정, 기능구현

#63 BE/feat/#55 세션 url 관련 기능 구현
  backend/src/main/java/com/rising/backend/domain/post/controller/PostController.java
  backend/src/main/java/com/rising/backend/domain/post/domain/Post.java
  backend/src/main/java/com/rising/backend/domain/post/domain/Session.java
  backend/src/main/java/com/rising/backend/domain/post/mapper/PostMapper.java
  backend/src/main/java/com/rising/backend/domain/post/service/PostService.java
  backend/src/main/java/com/rising/backend/global/result/ResultCode.java
  backend/src/main/java/com/rising/backend/global/util/UuidConverter.java
  backend/src/main/resources/application.yml
Labels: 기능구현

#66 FE/feat/#56 채팅 웹소켓 연결
  backend/gradlew
  backend/src/main/java/com/rising/backend/domain/chat/controller/ChatRoomController.java
  backend/src/main/java/com/rising/backend/domain/chat/controller/StompChatController.java
  backend/src/main/java/com/rising/backend/domain/chat/domain/ChatMessage.java
  backend/src/main/java/com/rising/backend/domain/chat/domain/ChatRoom.java
  backend/src/main/java/com/rising/backend/domain/chat/dto/ChatRoomDto.java
  backend/src/main/java/com/rising/backend/domain/chat/dto/MessageDto.java
  backend/src/main/java/com/rising/backend/domain/chat/mapper/ChatRoomMapper.java
  backend/src/main/java/com/rising/backend/domain/chat/repository/ChatRoomRepository.java
  backend/src/main/java/com/rising/backend/domain/chat/service/ChatRoomService.java
  backend/src/main/java/com/rising/backend/global/result/ResultCode.java
  backend/src/main/resources/application.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Chat/MyMessage.tsx
  frontend/src/components/Chat/OthersMessage.tsx
  frontend/src/index.tsx
  frontend/src/page/QuesChatPage.tsx
  frontend/src/utils/useInput.ts
Labels: 기능구현

#68 [Be/chore/#67] docker-compose RabbitMQ 세팅 추가
  .gitignore
  backend/src/main/java/com/rising/backend/global/constant/RabbitMQ.java
  backend/src/main/resources/application.yml
  docker-compose.yml
  nginx/dockerfile
  nginx/nginx.conf
Labels: 환경설정

#77 [BE/feat/#75] 채팅메세지 저장 기능 구현
  backend/src/main/java/com/rising/backend/domain/chat/controller/ChatRoomController.java
  backend/src/main/java/com/rising/backend/domain/chat/controller/WebSocketChatController.java
  backend/src/main/java/com/rising/backend/domain/chat/domain/ChatMessage.java
  backend/src/main/java/com/rising/backend/domain/chat/domain/ChatRoom.java
  backend/src/main/java/com/rising/backend/domain/chat/dto/ChatRoomDto.java
  backend/src/main/java/com/rising/backend/domain/chat/dto/MessageDto.java
  backend/src/main/java/com/rising/backend/domain/chat/mapper/ChatMessageMapper.java
  backend/src/main/java/com/rising/backend/domain/chat/mapper/ChatRoomMapper.java
  backend/src/main/java/com/rising/backend/domain/chat/repository/ChatMessageRepository.java
  backend/src/main/java/com/rising/backend/domain/chat/service/ChatMessageService.java
  backend/src/main/java/com/rising/backend/domain/chat/service/ChatRoomService.java
  frontend/src/page/QuesChatPage.tsx
Labels: 기능구현

#80 [FE/feat/#49] 로그인, 회원가입 페이지 퍼블리싱
  frontend/src/components/LoginBtn.tsx
  frontend/src/components/ProfileUpload.js
  frontend/src/images/BasicProfile.png
  frontend/src/page/AnsPage.tsx
  frontend/src/page/LoginPage.tsx
  frontend/src/page/PrivateAnsCheckPage.tsx
  frontend/src/page/PrivateAnsPage.tsx
  frontend/src/page/SignUpPage.tsx
Labels: 기능구현

#83 [BE/feat/#69] 코드 에디터 테스트를 위한 로직 작성
  backend/src/main/java/com/rising/backend/domain/chat/controller/WebSocketChatController.java
  backend/src/main/java/com/rising/backend/domain/sharecoding/controller/CodeController.java
  backend/src/main/java/com/rising/backend/domain/user/controller/UserController.java
  backend/src/main/java/com/rising/backend/global/config/RabbitConfig.java
  backend/src/main/java/com/rising/backend/global/result/ResultCode.java
  frontend/src/page/MentoringPage.tsx
Labels: 기능구현

#81 [BE/feat/#72] 채팅 메시지 불러오기 기능 구현
  backend/src/main/java/com/rising/backend/domain/chat/controller/ChatMessageController.java
  backend/src/main/java/com/rising/backend/domain/chat/dto/MessageDto.java
  backend/src/main/java/com/rising/backend/domain/chat/mapper/ChatMessageMapper.java
  backend/src/main/java/com/rising/backend/domain/chat/repository/ChatMessageRepository.java
  backend/src/main/java/com/rising/backend/domain/chat/service/ChatMessageService.java
  backend/src/main/java/com/rising/backend/global/result/ResultCode.java
Labels: 기능구현

#84 [FE/feat//#76] 과외 질문 상세 페이지
  backend/src/main/java/com/rising/backend/domain/sharecoding/domain/Operation.java
  frontend/src/page/AnsPage.tsx
  frontend/src/page/MentoringPage.tsx
  frontend/src/page/PrivateAnsCheckPage.tsx
  frontend/src/page/PrivateAnsPage.tsx
  frontend/src/page/PrivateQuesPage.tsx
  frontend/src/page/QuesChatPage.tsx
Labels: 기능구현

#88 [BE/feat/#86] post(게시글)의 키워드 설정 기능 구현
  backend/src/main/java/com/rising/backend/domain/post/controller/PostController.java
  backend/src/main/java/com/rising/backend/domain/post/domain/Post.java
  backend/src/main/java/com/rising/backend/domain/post/domain/Tag.java
  backend/src/main/java/com/rising/backend/domain/post/dto/PostDto.java
  backend/src/main/java/com/rising/backend/domain/post/mapper/PostMapper.java
  backend/src/main/java/com/rising/backend/domain/post/repository/PostRepository.java
  backend/src/main/java/com/rising/backend/domain/post/repository/TagRepository.java
  backend/src/main/java/com/rising/backend/domain/post/service/PostService.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/data.sql
Labels: 기능구현

#91 [BE/feat/#90] post 개별조회 Dto 작성날짜 추가, 전체조회 Dto 작성날짜 및 댓글수 추가
  backend/src/main/java/com/rising/backend/domain/comment/repository/CommentRepository.java
  backend/src/main/java/com/rising/backend/domain/post/dto/PostDto.java
  backend/src/main/java/com/rising/backend/domain/post/mapper/PostMapper.java
Labels: 기능구현

#94 [feat] 질문 리스트, 과외 질문 작성 및 답변 api 연결, 네비게이션 바 클릭 시 이동
  frontend/package-lock.json
  frontend/src/components/Editor/EditorViewer.tsx
  frontend/src/components/NavBar/NavBar.tsx
  frontend/src/components/NavBar/PrivateQuesNavBar.tsx
  frontend/src/components/NavBar/QuesListNavBar.tsx
  frontend/src/components/NavBar/QuesNavBar.tsx
  frontend/src/components/Ques.tsx
  frontend/src/components/Select/FrameWorkSelect.tsx
  frontend/src/components/Select/KeyWordOptionSelect.tsx
  frontend/src/components/Select/KeywordData.ts
  frontend/src/components/Select/KeywordSelect.tsx
  frontend/src/components/Select/QuesData.ts
  frontend/src/components/Tags/Date.tsx
  frontend/src/components/Tags/Tag.tsx
  frontend/src/page/AnsPage.tsx
  frontend/src/page/LoginPage.tsx
  frontend/src/page/MainPage.tsx
  frontend/src/page/MentoringPage.tsx
  frontend/src/page/MyPage.tsx
  frontend/src/page/PrivateAnsCheckPage.tsx
  frontend/src/page/PrivateAnsPage.tsx
  frontend/src/page/PrivateQuesPage.tsx
  frontend/src/page/QuesChatPage.tsx
  frontend/src/page/QuesListPage.tsx
  frontend/src/page/QuesPage.tsx
  frontend/src/page/SignUpPage.tsx
Labels: 기능구현

#97 Fe/feat/#82 Session 방식을 활용한 로그인 및 회원가입 api 연동 구현
  frontend/src/page/LoginPage.tsx
  frontend/src/page/SignUpPage.tsx
Labels: 기능구현

#96 [FE/feat/95] 질문 리스트 페이지 : 페이지네이션, ui 수정
  frontend/src/components/Ques.tsx
  frontend/src/components/Select/KeyWordOptionSelect.tsx
  frontend/src/components/Select/OptionSelect.tsx
  frontend/src/components/Tags/Date.tsx
  frontend/src/page/MentoringPage.tsx
  frontend/src/page/PrivateAnsCheckPage.tsx
  frontend/src/page/PrivateAnsPage.tsx
  frontend/src/page/PrivateQuesPage.tsx
  frontend/src/page/QuesChatPage.tsx
  frontend/src/page/QuesListPage.tsx
  frontend/src/page/QuesPage.tsx
Labels: 기능구현

#100 [FE/feat/#98] 일반 질문 페이지 api 연동 구현
  frontend/src/page/PrivateQuesPage.tsx
  frontend/src/page/QuesPage.tsx
Labels: 기능구현

#106 [BE/feat/#105] 로그인된 유저가 멘티인 채팅방 불러오기 api 구현
  backend/src/main/java/com/rising/backend/domain/chat/controller/ChatRoomController.java
  backend/src/main/java/com/rising/backend/domain/chat/dto/ChatRoomDto.java
  backend/src/main/java/com/rising/backend/domain/chat/mapper/ChatRoomMapper.java
  backend/src/main/java/com/rising/backend/domain/chat/repository/ChatRoomRepository.java
  backend/src/main/java/com/rising/backend/domain/chat/service/ChatRoomService.java
  backend/src/main/java/com/rising/backend/domain/post/dto/PostDto.java
  backend/src/main/java/com/rising/backend/domain/post/mapper/PostMapper.java
  backend/src/main/java/com/rising/backend/domain/user/dto/UserDto.java
  backend/src/main/java/com/rising/backend/domain/user/mapper/UserMapper.java
  backend/src/main/java/com/rising/backend/global/result/ResultCode.java
  backend/src/main/java/test.java
Labels: 기능구현

#108 [BE/feat/#107] 현재 로그인된 user가 mentor인 채팅방 조회
  backend/src/main/java/com/rising/backend/domain/chat/controller/ChatRoomController.java
  backend/src/main/java/com/rising/backend/domain/chat/repository/ChatRoomRepository.java
  backend/src/main/java/com/rising/backend/domain/chat/service/ChatRoomService.java
Labels: 기능구현

#111 [BE/feat/#104] 모니터링 프로그램 연동
  docker-compose.yml
  grafana/dashboards/nginx-monitoring.json
  grafana/datasource.yml
  nginx/nginx.conf
  prometheus/prometheus.yml
  prometheus/rules.yml
Labels: 기능구현

#113 [BE/fix/#112] comment get API response 수정
  backend/src/main/java/com/rising/backend/domain/comment/dto/CommentDto.java
  backend/src/main/java/com/rising/backend/domain/comment/mapper/CommentMapper.java
Labels: 리팩토링

#116 [FE/feat/#101] 일반 질문 <답변> 페이지 api 연동 구현
  frontend/src/components/Ans/Ans.tsx
  frontend/src/page/AnsPage.tsx
  frontend/src/page/QuesPage.tsx
Labels: 기능구현

#115 [FE/feat/#99] 채팅방 페이지 멘토와 멘티 구분, ui 수정, 페이지 이동 시 로컬 스토리지 사용
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Btn.tsx
  frontend/src/components/Chat/MyMessage.tsx
  frontend/src/components/Chat/OthersMessage.tsx
  frontend/src/components/ChatBox.tsx
  frontend/src/page/LoginPage.tsx
  frontend/src/page/MentoringPage.tsx
  frontend/src/page/MyPage.tsx
  frontend/src/page/PrivateAnsCheckPage.tsx
  frontend/src/page/PrivateAnsPage.tsx
  frontend/src/page/PrivateQuesPage.tsx
  frontend/src/page/QuesChatPage.tsx
  frontend/src/page/SignUpPage.tsx
Labels: 기능구현

#119 [FE/feat/#118] 일반 질문 답변 페이지 날짜, 시간 api 연결
  frontend/src/components/Ans/Ans.tsx
  frontend/src/page/AnsPage.tsx
Labels: 기능구현

#122 feat: user 정보 조회 (마이페이지) api
  backend/src/main/java/com/rising/backend/domain/user/controller/UserController.java
  backend/src/main/java/com/rising/backend/domain/user/dto/UserDto.java
  backend/src/main/java/com/rising/backend/domain/user/mapper/UserMapper.java
  backend/src/main/java/com/rising/backend/domain/user/repository/UserRepository.java
  backend/src/main/java/com/rising/backend/domain/user/service/UserService.java
  backend/src/main/java/com/rising/backend/global/result/ResultCode.java
Labels: 기능구현

#123 [FE/fix/#117] 프론트 배포 설정 수정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Ans/Ans.tsx
  frontend/src/components/MainMenu.tsx
  frontend/src/components/NavBar/NavBar.tsx
  frontend/src/components/NavBar/PrivateQuesNavBar.tsx
  frontend/src/components/NavBar/QuesListNavBar.tsx
  frontend/src/components/NavBar/QuesNavBar.tsx
  frontend/src/components/ProfileUpload.js
  frontend/src/components/ResentSlide.tsx
  frontend/src/images/Categori1.png
  frontend/src/images/Categori2.png
  frontend/src/images/Categori3.png
  frontend/src/images/Categori4.png
  frontend/src/images/Categori5.png
  frontend/src/images/dog.png
  frontend/src/images/profile.png
  frontend/src/page/AfterMainPage.tsx
  frontend/src/page/AnsPage.tsx
  frontend/src/page/BeforeMainPage.tsx
  frontend/src/page/LoginPage.tsx
  frontend/src/page/MainPage2.tsx
  frontend/src/page/MentoringPage.tsx
  frontend/src/page/MyPage.tsx
  frontend/src/page/PrivateAnsCheckPage.tsx
  frontend/src/page/PrivateAnsPage.tsx
  frontend/src/page/PrivateQuesPage.tsx
  frontend/src/page/QuesChatPage.tsx
  frontend/src/page/QuesListPage.tsx
  frontend/src/page/QuesPage.tsx
  frontend/src/page/SignUpPage.tsx
Labels: 오류수정, 환경설정

#127 [FE/feat/#125] 변경된 디자인으로 로그인 전후 메인페이지 퍼블리싱
  frontend/src/App.tsx
  frontend/src/images/icon1.png
  frontend/src/images/icon2.png
  frontend/src/images/icon3.png
  frontend/src/images/mentee.png
  frontend/src/images/mentor.png
  frontend/src/page/AfterMainPage.tsx
  frontend/src/page/BeforeMainPage.tsx
  frontend/src/page/LoginPage.tsx
  frontend/src/page/MainPage2.tsx
  frontend/src/utils/ColorSystem.tsx
Labels: 기능구현

#129 [FE/feat/#128] 메인페이지 동적인 css 추가
  frontend/src/page/AfterMainPage.tsx
  frontend/src/page/BeforeMainPage.tsx
  frontend/src/utils/pageStyle.css
  frontend/tailwind.config.js
Labels: 기능구현

#132 [FE/feat/#130] 반응형 퍼블리싱, ui 수정
  frontend/src/components/NavBar/NavBar.tsx
  frontend/src/components/NavBar/PrivateQuesNavBar.tsx
  frontend/src/components/NavBar/QuesListNavBar.tsx
  frontend/src/components/NavBar/QuesNavBar.tsx
  frontend/src/page/AfterMainPage.tsx
  frontend/src/page/BeforeMainPage.tsx
  frontend/src/page/QuesPage.tsx
  frontend/tailwind.config.js
Labels: 기능구현

#133 [FE/feat/#131] 잔여 페이지 반응형 퍼블리싱
  frontend/src/components/Ques.tsx
  frontend/src/components/Tags/Date.tsx
  frontend/src/components/Tags/Tag.tsx
  frontend/src/page/AnsPage.tsx
  frontend/src/page/MentoringPage.tsx
  frontend/src/page/PrivateAnsCheckPage.tsx
  frontend/src/page/PrivateAnsPage.tsx
  frontend/src/page/QuesChatPage.tsx
  frontend/src/page/QuesPage.tsx
Labels: 기능구현

#136 [Fix/#126] 웹소켓 관련 nginx.conf 수정 및 brokerurl 수정
  backend/src/main/java/com/rising/backend/global/config/StompConfig.java
  frontend/nginx.conf
  frontend/package-lock.json
  frontend/package.json
  frontend/src/page/QuesChatPage.tsx
Labels: 오류수정

#135 [FE/feat/#134] 댓글 useEffect 관련 랜더링 오류 해결
  frontend/src/page/AnsPage.tsx
Labels: 오류수정

#140 [FE/feat/#137] 폰트 적용
  frontend/public/index.html
  frontend/tailwind.config.js
Labels: 기능구현

#141 [FE/fix/#134] 댓글 작성 시 무한 요청 에러 해결
  frontend/src/page/AnsPage.tsx
  frontend/src/page/QuesPage.tsx
Labels: 오류수정

#142 [FE/feat/#138] 페이지 별 alert 알림 추가
  frontend/src/page/AnsPage.tsx
  frontend/src/page/PrivateQuesPage.tsx
  frontend/src/page/QuesPage.tsx
Labels: 기능구현
