Repository tukcom2023CD/RISING, pull requests merged in 2023-04, with the labels that each got.

#171 [FE/feat/#160] 코드에디터 충돌 방지 구현
  frontend/src/page/MentoringPage.tsx
Labels: 기능구현

#175 [BE/chore/#167] https 적용
  docker-compose.yml
  frontend/nginx.conf
  init-letsencrypt.sh
  nginx/init-letsencrypt.sh
Labels: 환경설정

#174 [BE/feat/#173] 채팅 및 유저 예외처리
  backend/src/main/java/com/rising/backend/domain/chat/exception/ChatRoomCreationFailedException.java
  backend/src/main/java/com/rising/backend/domain/chat/exception/ChatRoomNotFoundException.java
  backend/src/main/java/com/rising/backend/domain/chat/service/ChatMessageService.java
  backend/src/main/java/com/rising/backend/domain/chat/service/ChatRoomService.java
  backend/src/main/java/com/rising/backend/domain/user/controller/UserController.java
  backend/src/main/java/com/rising/backend/domain/user/exception/DuplicatedUsernameException.java
  backend/src/main/java/com/rising/backend/domain/user/exception/InvalidPasswordException.java
  backend/src/main/java/com/rising/backend/domain/user/exception/LoginRequiredException.java
  backend/src/main/java/com/rising/backend/domain/user/exception/UserNotFoundException.java
  backend/src/main/java/com/rising/backend/domain/user/service/UserService.java
  backend/src/main/java/com/rising/backend/global/error/ErrorCode.java
  backend/src/main/java/com/rising/backend/global/interceptor/LoginInterceptor.java
Labels: 기능구현

#180 [FE/feat/#179] 크롬 브라우저 한글 중복입력 오류 해결
  frontend/package-lock.json
  frontend/package.json
  frontend/src/page/MentoringPage.tsx
Labels: 오류수정

#184 [BE/feat/#183] login response body에 username추가
  backend/src/main/java/com/rising/backend/domain/user/controller/UserController.java
  backend/src/main/java/com/rising/backend/domain/user/dto/UserDto.java
Labels: 기능구현

#185 [FE/fix/#148] 채팅방 기능 안정화
  frontend/.eslintrc.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ChatBox.tsx
  frontend/src/components/redux/store.tsx
  frontend/src/components/redux/userSlice.tsx
  frontend/src/index.tsx
  frontend/src/page/AfterMainPage.tsx
  frontend/src/page/LoginPage.tsx
  frontend/src/page/MyPage.tsx
  frontend/src/page/PrivateAnsPage.tsx
  frontend/src/page/QuesChatPage.tsx
  frontend/src/page/SignUpPage.tsx
Labels: 오류수정

#188 [FE/feat/#178] 코드 에디터 변경 및 오류 수정
  frontend/package-lock.json
  frontend/package.json
  frontend/src/page/MentoringPage.tsx
  frontend/src/page/PrivateAnsPage.tsx
Labels: 기능구현
